project_id = "ijsxcaaqphaciaenlegl"

[functions.send-report-email]
verify_jwt = true

[functions.send-monthly-report]
verify_jwt = true

[functions.sync-ownerrez]
verify_jwt = true

[functions.charge-monthly-fees]
verify_jwt = true